server:
  port: 8080

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost

zuul:
  host:
    connect-request-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignored-services: '*'
  routes:
    public-service:
      path: /v1/**
      service-id: public-service
      strip-prefix: true
    person-service:
      path: /person/**
      service-id: person-service
      stripe-prefix: true
    address-service:
      path: /address/**
      service-id: adress-service
      stripe-prefix: true
    phone-service:
      path: /phone/**
      service-id: phone-service
      stripe-prefix: true